[tool.robocop.lint]
# Enable all rules (all categories, all severity levels: I, W, E)
select = [
    "*"
]

ignore = [
    "DOC03",  # Disable rule: missing-doc-in-suite
    "DOC04",  # Disable rule: missing-doc-resource-file
    "NAME02", # Disable rule: wrong-case-in-keyword-name
    "DEPR05", # Disable rule: use-replace-set-variable-with-var
    "NAME08", # Disable rule: section-variable-not-uppercase
    "SPC02",  # Disable rule: empty-lines-missing-trailing-blank-line
    "SPC03",  # Disable rule: empty-lines-between-sections
    "LEN04",  # Disable rule: test-case too long
    "LEN08",  # Disable rule: line-too-long
    "LEN06"   # Disable rule: too-many-calls-in-test-case
]
