device_capabilities:
  platform_name: Android
  automation_name: UiAutomator2
  platform_version: '16.0'
  device_name: DEVICE_NAME
  remote_url: http://127.0.0.1:4723
  btn_enter_key: 66
  newCommandTimeout: 3600
  adbExecTimeout: 60000
  uiautomator2ServerInstallTimeout: 60000
  uiautomator2ServerLaunchTimeout: 60000
  uiautomator2ServerReadTimeout: 60000
  autoGrantPermissions: true
  disableWindowAnimation: true
  noReset: false
  fullReset: false
app_capabilities:
  app_package: "com.shopee.th"
  app_activity: "com.shopee.app.ui.home.HomeActivity_"
swipe_screen:
  persent_start: 0.1
  persent_end: 0.7
tap_duration: 300ms
retries: 2
wait_duration: 1000ms
substring_config:
  first_string: 0
  last_string: 45