platform: android
platform_name: Android
tags: ts0
automation_name: UiAutomator2
platform_version: '16.0'
device_name: R5CW42DVEXV
remote_url: http://127.0.0.1:4723
app_package: "com.shopee.th"
app_activity: "com.shopee.app.ui.home.HomeActivity_"
