browser_type : chromium
headless_mode : false
wait_timeout:
  normally:
    mini_timeout: 03s
    short_timeout: 05s
    long_timeout: 10s
    very_long_timeout: 20s
    global_timeout: 30s
    timeout_forty: 40s  